version: '3.1'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=maha@ford
    ports:
      - '5431:5431'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local