server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookapplication
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: maha@ford
  jpa:
    hibernate:
      ddl-auto: update
